server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/COST_ADMINISTRATION?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: adam
    password: Test1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

logging:
  level:
    com.schindler: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

secret-key: '614E645267556B586E3272357538782F413F4428472B4B6250655368566D5971'
